version: '3.3'

services:

  nginx:
    container_name: nginx
    image: nginx:1.27.0
    volumes:
      - ./staticfiles:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    network_mode: host

  db:
    image: postgres:16.3
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: